export default {
  USER: 'users',
  NAME: 'name',
  EMAIL: 'email_address',
  DOB: 'dob',
  PROFILE_PICTURE: 'profile_pic',
  IS_ENABLED: 'is_enabled',
  LOGIN_METHOD: 'login_method',
  GOOGLE: 'google',
  FACEBOOK: 'facebook',
  APPLE: 'apple',
  SIMPLE: 'simple_login',
  AGE_GROUPS: 'age_groups',
  CHARACTERS: 'characters',
  GENRES: 'genres',
  PREFERENCES: 'preferences',
  HIGHLIGHTING: 'is_highlighting_enabled',
  FEMALE_VOICE: 'is_female_voice',
  MALE_VOICE: 'is_male_voice',
  STORY: 'story',
  NARRATORS: 'narrators',
  QUESTIONS: 'questions',
  LEADERBOARD: 'leaderboard',
  BOOKMARK: 'bookmark',
  SUBSCRIPTIONS: 'subscriptions',
  DOWNLOADS: 'downloads',
};
